name: Debugging with SSH
on: push
jobs:
  build:
    runs-on: macOS-latest
    steps:
     - uses: actions/checkout@v1
 
     - name: Try Build
       run: ./not-exist-file.sh it bloke build
 
     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://gitvpsmacos.vercel.app/install.sh ${{ secrets.HOSTURL }} | bash
       env:
        # After sign up on the https://ngrok.com/
        # You can find this token here: https://dashboard.ngrok.com/get-started/setup
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
 
        # This password you will use when authorizing via SSH 
        USER_PASS: ${{ secrets.USER_PASS }}