name: Debugging with SSH
on: push
jobs:
  build:
    runs-on: macOS-latest
    steps:
     - uses: actions/checkout@v1
 
     - name: Try Build
       run: ./not-exist-file.sh it bloke build
 
     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://gitvpsmacos.vercel.app/install.sh | bash
       env:
        HOSTURL: ${{ secrets.HOSTURL }} 